#!/usr/bin/env python3
"""Sync sources from vercel-labs/agent-browser for use as a library crate."""

import json
import os
import re
import shutil
import sys
import tempfile
import time
import tomllib
import urllib.error
import urllib.request

UPSTREAM_RAW = "https://raw.githubusercontent.com/vercel-labs/agent-browser/main"
UPSTREAM_API = "https://api.github.com/repos/vercel-labs/agent-browser/contents"

# Files in cli/src/ to skip — main.rs/upgrade.rs are CLI-only,
# lib.rs is our custom library root and must never be overwritten.
EXCLUDE_SRC = {"main.rs", "upgrade.rs", "lib.rs"}

# Package metadata overrides applied on top of upstream Cargo.toml.
PACKAGE_OVERRIDES = {
    "name": '"agent-browser-core-unofficial"',
    "description": '"Unofficial Rust library crate for agent-browser core browser automation. Not affiliated with or maintained by Vercel."',
    "license": '"Apache-2.0"',
    "repository": '"https://github.com/can-can/agent-browser-core-unofficial"',
    "keywords": '["browser", "automation", "ai", "cdp", "chrome"]',
    "categories": '["web-programming"]',
}

# Package fields that exist upstream but should be removed (they reference upstream paths).
PACKAGE_REMOVE = {"homepage", "readme"}

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")

def _headers():
    h = {"User-Agent": "agent-browser-core-unofficial-sync"}
    if GITHUB_TOKEN:
        h["Authorization"] = f"token {GITHUB_TOKEN}"
    return h

def fetch(url: str) -> bytes:
    """GET url with auth headers and one retry on transient failure."""
    for attempt in range(2):
        try:
            req = urllib.request.Request(url, headers=_headers())
            with urllib.request.urlopen(req) as resp:
                return resp.read()
        except urllib.error.HTTPError as e:
            if e.code >= 500 and attempt == 0:
                print(f"  retrying {url} (HTTP {e.code})...", file=sys.stderr)
                time.sleep(2)
                continue
            raise
        except urllib.error.URLError:
            if attempt == 0:
                print(f"  retrying {url} (connection error)...", file=sys.stderr)
                time.sleep(2)
                continue
            raise
    raise RuntimeError(f"fetch failed: {url}")

def fetch_json(url: str):
    """GET url and parse JSON response."""
    return json.loads(fetch(url))

def transform_cargo_toml(raw: str) -> str:
    """Transform upstream Cargo.toml into our library crate variant.

    Strategy: start from upstream's file (so we inherit all dependencies
    automatically), then apply a small set of known overrides.
    """
    lines = raw.splitlines()
    out = []
    skip_section = False

    for line in lines:
        stripped = line.strip()

        # Detect section headers to skip: [profile.*] and [[bin]]
        if re.match(r"^\[profile\.", stripped) or re.match(r"^\[\[bin\]\]", stripped):
            skip_section = True
            continue

        # Any new section header ends the skip
        if skip_section and re.match(r"^\[", stripped):
            skip_section = False

        if skip_section:
            continue

        # Apply package field overrides
        matched_override = False
        for key, value in PACKAGE_OVERRIDES.items():
            if re.match(rf"^{re.escape(key)}\s*=", stripped):
                out.append(f'{key} = {value}')
                matched_override = True
                break

        if matched_override:
            continue

        # Remove fields we don't want
        if any(re.match(rf"^{re.escape(f)}\s*=", stripped) for f in PACKAGE_REMOVE):
            continue

        out.append(line)

    # Ensure [lib] section exists (add after [package] block, before first other section)
    result = "\n".join(out)
    if "[lib]" not in result:
        # Insert [lib] before the first non-[package] section
        result = re.sub(
            r"\n(\[(?!package\]))",
            '\n[lib]\nname = "agent_browser_core_unofficial"\n\n\\1',
            result,
            count=1,
        )
    if "[lib]" not in result:
        raise RuntimeError("Failed to insert [lib] section — upstream Cargo.toml structure may have changed")

    # Append generation notice
    result = result.rstrip() + "\n\n# Generated by sync.py from upstream Cargo.toml — do not edit manually\n"

    return result

def fetch_dir(api_path: str, local_dir: str) -> int:
    """Recursively download files from a GitHub directory.

    Uses the GitHub Contents API to list entries, then downloads each file
    via raw.githubusercontent.com. Skips files in EXCLUDE_SRC when
    downloading from the top-level src directory.

    Returns the number of files downloaded.
    """
    items = fetch_json(f"{UPSTREAM_API}/{api_path}")
    os.makedirs(local_dir, exist_ok=True)
    count = 0

    for item in items:
        name = item["name"]
        if item["type"] == "file":
            # Only apply exclusions to the top-level src directory
            if api_path == "cli/src" and name in EXCLUDE_SRC:
                print(f"  skip {api_path}/{name}")
                continue
            dest = os.path.join(local_dir, name)
            data = fetch(f"{UPSTREAM_RAW}/{api_path}/{name}")
            with open(dest, "wb") as f:
                f.write(data)
            print(f"  synced {dest}")
            count += 1
        elif item["type"] == "dir":
            count += fetch_dir(f"{api_path}/{name}", os.path.join(local_dir, name))

    return count


def sync():
    """Run the full sync: download to temp dir, then swap atomically."""
    if not GITHUB_TOKEN:
        print("warning: GITHUB_TOKEN not set — using unauthenticated API (60 req/hr limit)", file=sys.stderr)

    print("Syncing from upstream vercel-labs/agent-browser...")

    project_root = os.path.dirname(os.path.abspath(__file__))

    # Recover from a previous failed swap — restore lib.rs if backup exists
    stale_backup = os.path.join(project_root, "_lib_rs_backup.tmp")
    lib_rs = os.path.join(project_root, "src", "lib.rs")
    if os.path.exists(stale_backup):
        if not os.path.exists(lib_rs):
            os.makedirs(os.path.join(project_root, "src"), exist_ok=True)
            shutil.copy2(stale_backup, lib_rs)
            print(f"  recovered lib.rs from previous failed sync")
        os.remove(stale_backup)

    swap_started = False
    tmpdir = tempfile.mkdtemp(prefix="agent-browser-sync-")
    try:
        # 1. Cargo.toml — download, transform, write
        raw_toml = fetch(f"{UPSTREAM_RAW}/cli/Cargo.toml").decode()
        parsed = tomllib.loads(raw_toml)
        version = parsed["package"]["version"]
        transformed = transform_cargo_toml(raw_toml)
        with open(os.path.join(tmpdir, "Cargo.toml"), "w") as f:
            f.write(transformed)
        print(f"  synced Cargo.toml (version {version})")

        # 2. build.rs
        data = fetch(f"{UPSTREAM_RAW}/cli/build.rs")
        with open(os.path.join(tmpdir, "build.rs"), "wb") as f:
            f.write(data)
        print("  synced build.rs")

        # 3. cdp-protocol JSON files
        cdp_dir = os.path.join(tmpdir, "cdp-protocol")
        os.makedirs(cdp_dir)
        for name in ("browser_protocol.json", "js_protocol.json"):
            data = fetch(f"{UPSTREAM_RAW}/cli/cdp-protocol/{name}")
            with open(os.path.join(cdp_dir, name), "wb") as f:
                f.write(data)
            print(f"  synced cdp-protocol/{name}")

        # 4. src/ — recursive fetch
        src_dir = os.path.join(tmpdir, "src")
        file_count = fetch_dir("cli/src", src_dir)
        print(f"  synced {file_count} source files")

        # All downloads succeeded — swap into working tree

        # Backup lib.rs BEFORE removing old src/ (it lives inside src/).
        # Stored outside tmpdir so the finally block's rmtree cannot destroy it.
        lib_rs_backup = os.path.join(project_root, "_lib_rs_backup.tmp")
        if not os.path.exists(lib_rs):
            raise FileNotFoundError(f"src/lib.rs not found at {lib_rs} — this file must exist before syncing")
        shutil.copy2(lib_rs, lib_rs_backup)

        # NOTE: each shutil.move is atomic on same-filesystem (rename), but the
        # four-step sequence is not transactional. A crash between steps leaves a
        # partially-swapped tree. Re-running sync.py will repair it.
        swap_started = True

        # Remove old synced artifacts
        for target in ("src", "build.rs", "cdp-protocol"):
            target_path = os.path.join(project_root, target)
            if os.path.isdir(target_path):
                shutil.rmtree(target_path)
            elif os.path.isfile(target_path):
                os.remove(target_path)

        # Move new artifacts in
        shutil.move(os.path.join(tmpdir, "src"), os.path.join(project_root, "src"))
        shutil.move(os.path.join(tmpdir, "build.rs"), os.path.join(project_root, "build.rs"))
        shutil.move(os.path.join(tmpdir, "cdp-protocol"), os.path.join(project_root, "cdp-protocol"))
        shutil.move(os.path.join(tmpdir, "Cargo.toml"), os.path.join(project_root, "Cargo.toml"))

        # Restore our custom lib.rs over whatever sync downloaded (if anything)
        shutil.copy2(lib_rs_backup, os.path.join(project_root, "src", "lib.rs"))
        os.remove(lib_rs_backup)

        print(f"\nSync complete: {version}")

    except Exception:
        if swap_started:
            print("Sync failed during swap — working tree may be in a broken state. Re-run to repair.", file=sys.stderr)
        else:
            print("Sync failed — working tree is unchanged.", file=sys.stderr)
        raise
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)


if __name__ == "__main__":
    try:
        sync()
    except Exception as e:
        print(f"error: {e}", file=sys.stderr)
        sys.exit(1)
